name: Deploy Flutter Web to GitHub Pages

on:
  push:
    branches: [ main ]      # เปลี่ยนเป็น master ถ้า repo คุณใช้ master
  workflow_dispatch:        # ให้กด Deploy เองได้จาก GitHub

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: 'stable'
          channel: 'stable'

      - name: Get dependencies
        run: flutter pub get

      - name: Build Flutter Web
        run: flutter build web --release --base-href "/${{ github.event.repository.name }}/" --web-renderer html

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./published/web
          force_orphan: true          # ทำให้ branch gh-pages สะอาด